package com.ibm.be.isco.shared.swagger;

import java.net.URI;

/** Swagger representation for a Problem */
public interface Problem {

  /**
   * An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide
   * human-readable documentation for the problem type (e.g., using HTML). When this member is not
   * present, its value is assumed to be "about:blank".
   */
  URI getType();

  /**
   * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to
   * occurrence of the problem, except for purposes of localisation.
   */
  String getTitle();

  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  int getStatus();

  /** A human readable explanation specific to this occurrence of the problem. */
  String getDetail();

  /**
   * An absolute URI that identifies the specific occurrence of the problem. It may or may not yield
   * further information if dereferenced.
   */
  URI getInstance();
}
